// mixed
export const DISPLAY_BUSINESS = 'DISPLAY_BUSINESS';

// businesses
export const STORE_BUSINESSES = 'STORE_BUSINESSES';
export const FETCHING_BUSINESS = 'FETCHING_BUSINESS';
export const BUSINESS_FETCHING_OFF = 'BUSINESS_FETCHING_OFF';
export const EXTEND_BUSINESS_INFO = 'EXTEND_BUSINESS_INFO';
export const DESELECT_BUSINESS = 'DESELECT_BUSINESS';

// search
export const ADD_SEARCH_ERROR = 'ADD_SEARCH_ERROR';
export const UPDATE_TERM = 'UPDATE_TERM';
export const UPDATE_LOCATION = 'UPDATE_LOCATION';
export const STORE_SEARCH_QUERY = 'STORE_SEARCH_QUERY';
export const DISPLAY_RESULTS = 'DISPLAY_RESULTS';
export const SEARCH_FETCHING_OFF = 'SEARCH_FETCHING_OFF';
export const FETCHING_RESULTS = 'FETCHING_RESULTS';
export const WIPE_SEARCH = 'WIPE_SEARCH';

// ui
export const DISPLAY_ERROR = 'DISPLAY_ERROR';
export const HIDE_ERROR = 'HIDE_ERROR';
